---
output: html_document
---

# clim4health_GET

The objective of clim4health_get is to download climate data from the Copernicus Climate Data Store (CDS). To access data from the CDS, authentication is required. In the function call you need to specify your personal access token and all details of the dataset you want. The function will save the dataset as a netcdf file in

---

## 1. Obtain your Personal Access Token (PAT)

---


If you don't already have an ECMWF account, you can go to the [ECMWF page](https://www.ecmwf.int/) and create a new account.
With these credentials you can now log into the [CDS](https://cds.climate.copernicus.eu/). Under "your profile", you can find your personal access token. Save your personal access token, you will need it in [step 4](##-4.-Get-the-data)

#### Using Non European contributions

If you will be using Non European contributions, such as XXX. Then you need to agree to the additional dataset license, which you can find under your profile too.

---

## 2. Working directory and library dependencies

---

Obtain current path, which need to be the path where the clim4health repository is cloned, and source the *clim4health_get* function

```r
path <- getwd()
source(paste0(path, '/functions/clim4health_get.R'))        
```

At the moment the function is loaded, the dependencies will also be loaded, if some error occurs, make sure that all the necessary dependencies are installed:

```r
install.packages("ecmwfr")
library(ecmwfr)
```

## 3. Decide what data you need

If you already know which datasets, variables and parameters you require can skip this step.

To know what to ask for in the function, you can use clim4health_get_help().
If the function is run without any parameters, it will return the datasets that are currently available to download within clim4health. It will look like this

``` r
> clim4health_get_help()
Available climate datasets:
- reanalysis-era5-land 
- reanalysis-era5-land-monthly-means 
- reanalysis-era5-single-levels 
- reanalysis-era5-single-levels-monthly-means 
- seasonal-monthly-single-levels 
```

Once you know what dataset you will be using, you can run the function with your selected dataset as a parameter to obtain the required parameters needed to download it. It look like follows:

```r
> clim4health_get_help("reanalysis-era5-land")
Required parameters:
- product_type
- variables 
- year
- month 
```

Finally, each dataset can have a different set of required parameters. All require a set time period and spatial extent, other may require additional information such as 

```r
> clim4health_get_help("reanalysis-era5-land", "variable")
Possible options for variables:
- 2m_dewpoint_temperature 
- 2m_temperature 
- skin_temperature 
- soil_temperature_level_1 
- soil_temperature_level_2 
...
```

---

## 4. Get the data

---

Once you know your PAT, the dataset, and the required parameters you can call clim4health like you can see below. In these 3 examples, you will download reanalysis data from era5land, and the seasonal forecats, once as hindcast and once as forecast.
These will be the sample data that the rest of the functions are working with.

```r
clim4health_get(pat = "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
                dataset = "reanalysis-era5-land-monthly-means",
                product_type = "monthly_averaged_reanalysis",
                variable = "2m_temperature",
                year = c(2010, 2011, 2012),
                month = c(4, 5),
                area = c(33, -93, -23, -17),
                outname = "era5land")
```

```r
clim4health_get(pat = "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
                dataset = "seasonal-monthly-single-levels",
                originating_centre = c("ecmwf"),
                system = c("51"),
                variable = c("2m_temperature"),
                product_type = c("monthly_mean"),
                year = c("2010", "2011", "2012"),
                month = c("04"),
                leadtime_month = c("1", "2", "3"),
                area = c(33, -93, -23, -17),
                outname = "hindcast")
```

```r
clim4health_get(pat = "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
                dataset = "seasonal-monthly-single-levels",
                originating_centre = c("ecmwf"),
                system = c("51"),
                variable = c("2m_temperature"),
                product_type = c("monthly_mean"),
                year = c("2024"),
                month = c("04"),
                leadtime_month = c("1", "2", "3"),
                area = c(33, -93, -23, -17),
                outname = "forecast")
```



<!-- ## Potential errorsNon European contributions, -->

<!-- ``` -->
<!-- Error: permission deniedrequired licences not accepted403Not all the required licences have been accepted; please visit https://cds.climate.copernicus.eu/datasets/seasonal-monthly-single-levels?tab=download#manage-licences to accept the required licence(s).https://cds.climate.copernicus.eu/api/retrieve/v1/processes/seasonal-monthly-single-levels/executeeca44435-0976-4e4f-b864-a3c43d108ba4 -->
<!-- ``` -->
<!-- if this fails, you may need to accept a special license at this link: https://cds.climate.copernicus.eu/datasets/seasonal-monthly-single-levels?tab=download#manage-licences -->
